import AppLayout from "@/layout";
import { Public_Sans } from "next/font/google";
import "./styles/globals.css";

const font_family = Public_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-dark min-h-screen ${font_family.className}`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
